In [1]:
import torch
import numpy as np

In [2]:
a = torch.FloatTensor([1,2,3])

In [3]:
b = torch.FloatTensor([4,5,6])

In [4]:
a

tensor([1., 2., 3.])

In [5]:
b

tensor([4., 5., 6.])

In [6]:
a * b

tensor([ 4., 10., 18.])

In [7]:
a.dot(b)

tensor(32.)

In [8]:
a.shape

torch.Size([3])

In [9]:
b.shape

torch.Size([3])

In [10]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [11]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [12]:
b = torch.tensor([[3,2],[5,6],[7,8]])

In [13]:
b

tensor([[3, 2],
        [5, 6],
        [7, 8]])

In [14]:
a.shape

torch.Size([2, 3])

In [15]:
b.shape

torch.Size([3, 2])

In [19]:
torch.mm(a,b)

tensor([[38, 44],
        [53, 60]])

In [20]:
a @ b

tensor([[38, 44],
        [53, 60]])

In [21]:
a.mm(b)

tensor([[38, 44],
        [53, 60]])

In [22]:
x = torch.FloatTensor([2,3,4,5])

In [23]:
x.norm()

tensor(7.3485)

In [24]:
x.numel()

4

In [25]:
len(x)

4

In [26]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [27]:
len(a) # no of rows

2

In [28]:
a.numel() # no of elements

6