In [1]:
import numpy as np
import torch

In [9]:
torch.manual_seed(42)

In [10]:
arr = torch.randint(low=0, high=6, size=(6,))

In [11]:
arr

tensor([0, 5, 4, 4, 0, 5])

In [12]:
arr.dtype

torch.int64

In [15]:
x = arr.type(torch.int32)

In [16]:
x = x.reshape(3,2)

In [17]:
x

tensor([[0, 5],
        [4, 4],
        [0, 5]], dtype=torch.int32)

In [18]:
x[:,1:]

tensor([[5],
        [4],
        [5]], dtype=torch.int32)

In [19]:
x.pow_(2)

tensor([[ 0, 25],
        [16, 16],
        [ 0, 25]], dtype=torch.int32)

In [21]:
y = torch.randint_like(x, low=0, high=5)

In [22]:
y

tensor([[0, 4],
        [0, 3],
        [3, 4]], dtype=torch.int32)

In [23]:
y = y.reshape(2,3)

In [24]:
y

tensor([[0, 4, 0],
        [3, 3, 4]], dtype=torch.int32)

In [26]:
x @ y

tensor([[ 75,  75, 100],
        [ 48, 112,  64],
        [ 75,  75, 100]], dtype=torch.int32)

In [27]:
y.T

tensor([[0, 3],
        [4, 3],
        [0, 4]], dtype=torch.int32)

In [28]:
x

tensor([[ 0, 25],
        [16, 16],
        [ 0, 25]], dtype=torch.int32)

In [29]:
y

tensor([[0, 4, 0],
        [3, 3, 4]], dtype=torch.int32)